# Clean Mise Configuration - Minimal Setup

[settings]
experimental = true
quiet = false

[tools]
node = "22.19.0"
usage = "latest"
uv = "latest"

# Start with no global tools - install as needed
# [tools]
