# Desktop Host Configuration
{ config, lib, pkgs, inputs, ... }:

{
  imports = [
    # Hardware configuration will be generated by nixos-generate-config
    # ./hardware-configuration.nix
  ];

  # System configuration
  system.stateVersion = "24.05"; # Set to your NixOS version
  
  # Networking
  networking = {
    hostName = "nixos-desktop"; # Change to your hostname
    networkmanager.enable = true;
    firewall.enable = true;
  };

  # Bootloader
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  # Time zone and locale
  time.timeZone = "America/Phoenix"; # Change to your timezone
  i18n.defaultLocale = "en_US.UTF-8";

  # User configuration
  users.users.derrick = {
    isNormalUser = true;
    description = "Derrick";
    extraGroups = [ "networkmanager" "wheel" "video" "audio" "input" ];
    shell = pkgs.fish;
  };

  # Enable our custom modules
  desktop = {
    hyprland = {
      enable = true;
      nvidia = false; # Set to true if using NVIDIA
    };
    
    sddm = {
      enable = true;
      theme = "catppuccin-macchiato-blue";
    };
    
    waybar.enable = true;
  };

  programs = {
    development.enable = true;
    shells.enable = true;
  };

  themes.catppuccin = {
    enable = true;
    flavor = "macchiato";
    accent = "blue";
  };

  # Allow unfree packages (for proprietary software)
  nixpkgs.config.allowUnfree = true;

  # Flake support
  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;
    };
    
    # Automatic garbage collection
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 30d";
    };
  };

  # System packages
  environment.systemPackages = with pkgs; [
    # Basic utilities
    wget
    curl
    git
    vim
    htop
    tree
    unzip
    
    # System tools
    pciutils
    usbutils
    lshw
    
    # Network tools
    networkmanager
  ];
}
