# Starship Configuration with Catppuccin Macchiato Theme
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Use custom format
format = """
[╭─user───❯](bold blue) $username$hostname$directory$git_branch$git_status$package$nodejs$python$rust$golang$java$docker_context
[╰─](bold blue)$character"""

# Disable the blank line at the start of the prompt
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[username]
style_user = "bold teal"
style_root = "bold red"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](bold blue) "
trim_at = ".companyname.com"
disabled = false

[directory]
style = "bold peach"
format = "in [$path]($style)[$lock_symbol]($lock_style) "
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"

[git_branch]
symbol = " "
style = "bold mauve"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "[$all_status$ahead_behind]($style) "
conflicted = "⚡"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = "$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[nodejs]
symbol = " "
style = "bold green"
format = "via [$symbol($version )]($style)"

[python]
symbol = " "
style = "bold yellow"
format = "via [$symbol$pyenv_prefix($version )(\($virtualenv\) )]($style)"

[rust]
symbol = " "
style = "bold red"
format = "via [$symbol($version )]($style)"

[golang]
symbol = " "
style = "bold cyan"
format = "via [$symbol($version )]($style)"

[java]
symbol = " "
style = "bold red"
format = "via [$symbol($version )]($style)"

[docker_context]
symbol = " "
style = "bold blue"
format = "via [$symbol$context]($style) "
only_with_files = true

[cmd_duration]
style = "bold yellow"
format = "took [$duration]($style) "
min_time = 4_000

[jobs]
style = "bold blue"
symbol = ""
number_threshold = 1
format = "[$symbol$number]($style) "

# Catppuccin Macchiato Colors
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

# Use the Catppuccin Macchiato palette
palette = "catppuccin_macchiato"
