#+TITLE: IRON-EMACS GNU Emacs Config
#+AUTHOR: Derrick Southworth (iron-tower-dev)
#+DESCRIPTION: My personal Emacs config.
#+STARTUP: showeverything
#+OPTIONS: toc:2

* TABLE OF CONTENTS :toc:
- [[#important-programs-to-load-first][IMPORTANT PROGRAMS TO LOAD FIRST]]
  - [[#adding-the-scripts-directory-to-path][Adding the scripts directory to path]]
  - [[#sourcing-the-scripts][Sourcing the scripts]]
- [[#all-the-icons][ALL THE ICONS]]
- [[#backup][BACKUP]]
- [[#company][COMPANY]]
- [[#dashboard][DASHBOARD]]
- [[#diminish][DIMINISH]]
- [[#dired][DIRED]]
- [[#elfeed][ELFEED]]
- [[#evil][EVIL]]
- [[#flycheck][FLYCHECK]]
- [[#fonts][FONTS]]
  - [[#setting-the-font-face][Setting the Font Face]]
  - [[#zooming-inout][Zooming In/Out]]
- [[#general-keybindings][GENERAL KEYBINDINGS]]
- [[#git-programs][GIT PROGRAMS]]
  - [[#git-time-machine][Git Time Machine]]
  - [[#magit][Magit]]
- [[#highlight-todo][HIGHLIGHT TODO]]
- [[#ivy-counsel][IVY (COUNSEL)]]
- [[#language-support][LANGUAGE SUPPORT]]
  - [[#golang-config][Golang Config]]
- [[#minibuffer-escape][MINIBUFFER ESCAPE]]
- [[#modeline][MODELINE]]
- [[#neotree][NEOTREE]]
- [[#org-mode][ORG MODE]]
  - [[#enabling-table-of-contents][Enabling Table of Contents]]
  - [[#enabling-org-bullets][Enabling Org Bullets]]
  - [[#diminish-org-indent-mode][Diminish Org Indent Mode]]
  - [[#org-level-headers][Org Level Headers]]
  - [[#source-code-block-tag-expansion][Source Code Block Tag Expansion]]
- [[#perspective][PERSPECTIVE]]
- [[#projectile][PROJECTILE]]
- [[#rainbow-mode][RAINBOW MODE]]
- [[#sane-defaults][SANE DEFAULTS]]
- [[#shells-and-terminals][SHELLS AND TERMINALS]]
  - [[#eshell][Eshell]]
  - [[#vterm][Vterm]]
  - [[#vterm-toggle][Vterm-Toggle]]
- [[#sudo-edit][SUDO EDIT]]
- [[#theme][THEME]]
- [[#tldr][TLDR]]
- [[#transparency][TRANSPARENCY]]
- [[#which-key][WHICH-KEY]]

* IMPORTANT PROGRAMS TO LOAD FIRST
To keep this =config.org= a reasonable length, I have moved a lot of code to individual scripts that will be sourced by this config.  These scripts are found in "~/.config/emacs/scripts" and do not contain any code that most people are likely to need to edit.

** Adding the scripts directory to path
#+begin_src emacs-lisp
  (add-to-list 'load-path "~/.config/emacs/scripts/")
#+end_src

** Sourcing the scripts
#+begin_src emacs-lisp
  (require 'elpaca-setup)  ;; The Elpaca Package Manager
  (require 'buffer-move)   ;; Buffer-move for better window management
  (require 'app-launchers) ;; Use emacs as a run launcher like dmenu (experimental)
#+end_src

* ALL THE ICONS
This is an icon set that can be used with dashboard, dired, ibuffer and other Emacs programs.
  
#+begin_src emacs-lisp
  (use-package all-the-icons
    :ensure t
    :if (display-graphic-p))

  (use-package all-the-icons-dired
    :ensure t
    :hook (dired-mode . (lambda () (all-the-icons-dired-mode t))))
#+end_src

* BACKUP 
By default, Emacs creates automatic backups of files in their original directories, such "file.el" and the backup "file.el~".  This leads to a lot of clutter, so let's tell Emacs to put all backups that it creates in the =TRASH= directory.

#+begin_src emacs-lisp
  (setq backup-directory-alist '((".*" . "~/.Trash")))
#+end_src

* COMPANY
[[https://company-mode.github.io/][Company]] is a text completion framework for Emacs. The name stands for "complete anything".  Completion will start automatically after you type a few letters. Use M-n and M-p to select, <return> to complete or <tab> to complete the common part.

#+begin_src emacs-lisp
(use-package company
  :ensure t
  :defer 2
  :diminish
  ;; go autocomplete
  :hook (go-mode . company-mode)
  :custom
  (company-begin-commands '(self-insert-command))
  (company-idle-delay .1)
  (company-minimum-prefix-length 2)
  (company-show-numbers t)
  (company-tooltip-align-annotations 't)
  (global-company-mode t))

(use-package company-box
  :after company
  :ensure t
  :diminish
  :hook (company-mode . company-box-mode))
#+end_src

* DASHBOARD
Emacs Dashboard is an extensible startup screen showing you recent files, bookmarks, agenda items and an Emacs banner.

#+begin_src emacs-lisp
  (use-package dashboard
    :ensure t 
    :demand t
    :init
    (setq initial-buffer-choice 'dashboard-open)
    (setq dashboard-set-heading-icons t)
    (setq dashboard-set-file-icons t)
    (setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")
    ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
    (setq dashboard-startup-banner "/home/derrick/.config/emacs/images/emacs-dash.png")  ;; use custom image as banner
    (setq dashboard-center-content nil) ;; set to 't' for centered content
    (setq dashboard-items '((recents . 5)
                            (agenda . 5 )
                            (bookmarks . 3)
                            (projects . 3)
                            (registers . 3)))
    :custom
    (dashboard-modify-heading-icons '((recents . "file-text")
                                      (bookmarks . "book")))
    :config
    (dashboard-setup-startup-hook))
#+end_src

* DIMINISH
This package implements hiding or abbreviation of the modeline displays (lighters) of minor-modes.  With this package installed, you can add ':diminish' to any use-package block to hide that particular mode in the modeline.

#+begin_src emacs-lisp
  (use-package diminish :ensure t)
#+end_src

* DIRED
#+begin_src emacs-lisp
  (use-package dired-open
    :ensure t
    :config
    (setq dired-open-extensions '(("gif" . "sxiv")
                                  ("jpg" . "sxiv")
                                  ("png" . "sxiv")
                                  ("mkv" . "mpv")
                                  ("mp4" . "mpv"))))

  (use-package peep-dired
    :after dired
    :ensure t
    :hook (evil-normalize-keymaps . peep-dired-hook)
    :config
      (evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory)
      (evil-define-key 'normal dired-mode-map (kbd "l") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
      (evil-define-key 'normal peep-dired-mode-map (kbd "j") 'peep-dired-next-file)
      (evil-define-key 'normal peep-dired-mode-map (kbd "k") 'peep-dired-prev-file)
  )

  ;;(add-hook 'peep-dired-hook 'evil-normalize-keymaps)
#+end_src

* ELFEED
An RSS newsfeed reader for Emacs.  Move through the articles with 'j/k'.  Move through the stories with 'CTRL j/k' when in other frame.

#+begin_src emacs-lisp
  (use-package elfeed
    :ensure t
    :config
    (setq elfeed-search-feed-face ":foreground #ffffff :weight bold"
          elfeed-feeds (quote
                         (("https://www.reddit.com/r/linux.rss" reddit linux)
                          ("https://www.reddit.com/r/commandline.rss" reddit commandline)
                          ("https://www.reddit.com/r/distrotube.rss" reddit distrotube)
                          ("https://www.reddit.com/r/emacs.rss" reddit emacs)
                          ("https://www.gamingonlinux.com/article_rss.php" gaming linux)
                          ("https://hackaday.com/blog/feed/" hackaday linux)
                          ("https://opensource.com/feed" opensource linux)
                          ("https://linux.softpedia.com/backend.xml" softpedia linux)
                          ("https://itsfoss.com/feed/" itsfoss linux)
                          ("https://www.zdnet.com/topic/linux/rss.xml" zdnet linux)
                          ("https://www.phoronix.com/rss.php" phoronix linux)
                          ("http://feeds.feedburner.com/d0od" omgubuntu linux)
                          ("https://www.computerworld.com/index.rss" computerworld linux)
                          ("https://www.networkworld.com/category/linux/index.rss" networkworld linux)
                          ("https://www.techrepublic.com/rssfeeds/topic/open-source/" techrepublic linux)
                          ("https://betanews.com/feed" betanews linux)
                          ("http://lxer.com/module/newswire/headlines.rss" lxer linux)
                          ("https://distrowatch.com/news/dwd.xml" distrowatch linux)))))
   
  (use-package elfeed-goodies
    :ensure t
    :demand t
    :init
    (elfeed-goodies/setup)
    :config
    (setq elfeed-goodies/entry-pane-size 0.5))
#+end_src

* EVIL
[[https://github.com/emacs-evil/evil][Evil]] is an extensible vi/vim layer for Emacs.  Because...let's face it.  The Vim keybindings are just plain better.

#+begin_src emacs-lisp
  (use-package evil
      :ensure t
      :demand t
      :init      ;; tweak evil's configuration before loading it
      (setq evil-want-integration t) ;; This is optional since it's already set to t by default.
      (setq evil-want-keybinding nil)
      (setq evil-vsplit-window-right t)
      (setq evil-split-window-below t)
      (evil-mode))
    (use-package evil-collection
      :after evil
      :ensure t
      :config
      (setq evil-collection-mode-list '(dashboard dired ibuffer))
      (evil-collection-init))
    (use-package evil-tutor :ensure t)
#+end_src

* FLYCHECK
Install =luacheck= from your Linux distro's repositories for flycheck to work correctly with lua files.  Install =python-pylint= for flycheck to work with python files.  Haskell works with flycheck as long as =haskell-ghc= or =haskell-stack-ghc= is installed.  For more information on language support for flycheck, [[https://www.flycheck.org/en/latest/languages.html][read this]].

#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :demand t
  :defer t
  :diminish
  ;; go syntax checking
  :hook (go-mode . flycheck-mode)
  :init (global-flycheck-mode))
#+end_src

* FONTS
Defining the various fonts that Emacs will use.

** Setting the Font Face
#+begin_src emacs-lisp
  (set-face-attribute 'default nil
    :font "JetBrains Mono"
    :height 110
    :weight 'medium)
  (set-face-attribute 'variable-pitch nil
    :font "Ubuntu"
    :height 120
    :weight 'medium)
  (set-face-attribute 'fixed-pitch nil
    :font "JetBrains Mono"
    :height 110
    :weight 'medium)
  ;; Makes commented text and keywords italics.
  ;; This is working in emacsclient but not emacs.
  ;; Your font must have an italic face available.
  (set-face-attribute 'font-lock-comment-face nil
    :slant 'italic)
  (set-face-attribute 'font-lock-keyword-face nil
    :slant 'italic)

  ;; This sets the default font on all graphical frames created after restarting Emacs.
  ;; Does the same thing as 'set-face-attribute default' above, but emacsclient fonts
  ;; are not right unless I also add this method of setting the default font.
  (add-to-list 'default-frame-alist '(font . "JetBrains Mono-11"))

  ;; Uncomment the following line if line spacing needs adjusting.
  (setq-default line-spacing 0.12)
#+end_src

** Zooming In/Out
You can use the bindings CTRL plus =/- for zooming in/out.  You can also use CTRL plus the mouse wheel for zooming in/out.

#+begin_src emacs-lisp
  (global-set-key (kbd "C-=") 'text-scale-increase)
  (global-set-key (kbd "C--") 'text-scale-decrease)
  (global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
  (global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
#+end_src

* GENERAL KEYBINDINGS

#+begin_src emacs-lisp
  (use-package general
    :ensure t
    :config
    (general-evil-setup)

    ;; set up 'SPC' as the global leader key
    (general-create-definer iron/leader-keys
      :states '(normal insert visual emacs)
      :keymaps 'override
      :prefix "SPC" ;; set leader
      :global-prefix "M-SPC") ;; access leader in insert mode
    
    (iron/leader-keys
      "SPC" '(counsel-M-x :wk "Counsel M-x")
      "." '(find-file :wk "Find file")
      "=" '(perspective-map :wk "Perspective") ;; Lists all the perspective keybindings
      "TAB TAB" '(comment-line :wk "Comment lines")
      "u" '(universal-argument :wk "Universal argument"))

    (iron/leader-keys
      "b" '(:ignore t :wk "[B]uffer")
      "b c" '(clone-indirect-buffer :wk "Create indirect buffer [C]opy in a split")
      "b C" '(clone-indirect-buffer-other-window :wk "[C]lone indirect buffer in new window")
      "b d" '(bookmark-delete :wk "Delete bookmark")
      "b i" '(ibuffer :wk "[I]buffer")
      "b k" '(kill-this-buffer :wk "[K]ill this buffer")
      "b K" '(kill-some-buffers :wk "[K]ill multiple buffers")
      "b l" '(list-bookmarks :wk "[L]ist bookmarks")
      "b m" '(bookmark-set :wk "Set book[M]ark")
      "b n" '(next-buffer :wk "[N]ext buffer")
      "b p" '(previous-buffer :wk "[P]revious buffer")
      "b r" '(revert-buffer :wk "[R]eload buffer")
      "b R" '(rename-buffer :wk "[R]ename buffer")
      "b s" '(basic-save-buffer :wk "[S]ave buffer")
      "b S" '(save-some-buffers :wk "[S]ave multiple buffers")
      "b w" '(bookmark-save :wk "[W]rite/Save current bookmarks to bookmark file"))
    
    (iron/leader-keys
      "d" '(:ignore t :wk "[D]ired")
      "d d" '(dired :wk "Open [D]ired")
      "d j" '(dired-jump :wk "Dired [J]ump to current")
      "d n" '(neotree-dir :wk "Open directory in [N]eotree")
      "d p" '(peep-dired :wk "Peep-dired"))
    
    (iron/leader-keys
      "e" '(:ignore t :wk "[E]shell/[E]valuate")    
      "e b" '(eval-buffer :wk "Evaluate elisp in [B]uffer")
      "e d" '(eval-defun :wk "Evaluate [D]efun containing or after point")
      "e e" '(eval-expression :wk "Evaluate and elisp [E]xpression")
      "e h" '(counsel-esh-history :wk "Eshell [H]istory")
      "e l" '(eval-last-sexp :wk "Evaluate [L]ast elisp expression before point")
      "e r" '(eval-region :wk "Evaluate elisp in [R]egion")
      "e R" '(eww-reload :which-key "[R]eload current page in EWW")
      "e s" '(eshell :wk "E[S]hell")
      "e w" '(eww :wk "EWW emacs [W]eb browser"))

    (iron/leader-keys
      "f" '(:ignore t :wk "[F]iles")
      "f c" '((lambda () (interactive) 
  	      (find-file "~/.config/emacs/iron-emacs.org")) 
  	    :wk "[F]ind emacs [C]onfig")
      "f e" '((lambda () (interactive)
  	      (dired "~/.config/emacs/"))
  	    :wk "Open user-[E]macs-directory in dired")
      "f d" '(find-grep-dired :wk "Search for string in files in [D]IR")
      "f g" '(counsel-grep-or-swiper :wk "[G]rep for string in current file")
      "f i" '((lambda () (interactive)
  	      (find-file "~/.config/emacs/init.el"))
  	    :wk "Open emacs [I]nit.el")
      "f j" '(counsel-file-jump :wk "[J]ump to a file below current directory")
      "f l" '(counsel-locate :wk "[L]ocate a file")
      "f r" '(counsel-recentf :wk "Find [R]ecent files")
      "f u" '(sudo-edit-find-file :wk "S[U]do find file")
      "f U" '(sudo-edit :wk "S[U]do edit file"))
    
    (iron/leader-keys
      "g" '(:ignore t :wk "[G]it")    
      "g /" '(magit-displatch :wk "Magit dispatch [/]")
      "g ." '(magit-file-displatch :wk "Magit file dispatch [.]")
      "g b" '(magit-branch-checkout :wk "Switch [B]ranch")
      "g c" '(:ignore t :wk "[C]reate") 
      "g c b" '(magit-branch-and-checkout :wk "Create [B]ranch and checkout")
      "g c c" '(magit-commit-create :wk "Create [C]ommit")
      "g c f" '(magit-commit-fixup :wk "Create [F]ixup commit")
      "g C" '(magit-clone :wk "[C]lone repo")
      "g f" '(:ignore t :wk "[F]ind") 
      "g f c" '(magit-show-commit :wk "Show [C]ommit")
      "g f f" '(magit-find-file :wk "Magit find [F]ile")
      "g f g" '(magit-find-git-config-file :wk "Find [G]itconfig file")
      "g F" '(magit-fetch :wk "Git [F]etch")
      "g g" '(magit-status :wk "Ma[G]it status")
      "g i" '(magit-init :wk "[I]nitialize git repo")
      "g l" '(magit-log-buffer-file :wk "Magit buffer [L]og")
      "g r" '(vc-revert :wk "Git [R]evert file")
      "g s" '(magit-stage-file :wk "Git [S]tage file")
      "g t" '(git-timemachine :wk "Git [T]ime machine")
      "g u" '(magit-stage-file :wk "Git [U]nstage file"))

    (iron/leader-keys
      "h" '(:ignore t :wk "[H]elp")  
      "h a" '(counsel-apropos :wk "[A]propos")
      "h b" '(describe-bindings :wk "Describe [B]indings")
      "h c" '(describe-char :wk "Describe [C]haracter under cursor")
      "h d" '(:ignore t :wk "Emacs [D]ocumentation")
      "h d a" '(about-emacs :wk "[A]bout Emacs")
      "h d d" '(view-emacs-debugging :wk "View Emacs [D]ebugging")
      "h d f" '(view-emacs-FAQ :wk "View Emacs [F]AQ")
      "h d m" '(info-emacs-manual :wk "The Emacs [M]anual") 
      "h d n" '(view-emacs-news :wk "View Emacs [N]ews")
      "h d o" '(describe-distribution :wk "How to [O]btain Emacs")
      "h d p" '(view-emacs-problems :wk "View Emacs [P]roblems")
      "h d t" '(view-emacs-todo :wk "View Emacs [T]odo")
      "h d w" '(describe-no-warranty :wk "Describe no [W]arranty")
      "h e" '(view-echo-area-messages :wk "View [E]cho area messages")
      "h f" '(describe-function :wk "Describe [F]unction")
      "h F" '(describe-face :wk "Describe [F]ace")
      "h g" '(describe-gnu-project :wk "Describe [G]NU Project")
      "h i" '(info :wk "[I]nfo")
      "h I" '(describe-input-method :wk "Describe [I]nput method")
      "h k" '(describe-key :wk "Describe [K]ey")
      "h l" '(view-lossage :wk "Display recent keystrokes and the commands run")
      "h L" '(describe-language-environment :wk "Describe [L]anguage environment")
      "h m" '(describe-mode :wk "Describe [M]ode")
      "h r" '(:ignore t :wk "[R]eload")
      "h r r" '((lambda () (interactive)
  		(load-file "~/.config/emacs/init.el")
  		(ignore (elpaca-process-queues)))
                :wk "Reload emacs config")
      "h t" '(load-theme :wk "Load [T]heme")
      "h v" '(describe-variable :wk "Describe [V]ariable")
      "h w" '(where-is :wk "Prints keybinding for command if set")
      "h x" '(describe-command :wk "Display full documentation for command"))
   
   (iron/leader-keys
      "m" '(:ignore t :wk "Org")
      "m a" '(org-agenda :wk "Org [A]genda")
      "m e" '(org-export-dispatch :wk "Org [E]xport dispatch")
      "m i" '(org-toggle-item :wk "Org toggle [I]tem")
      "m t" '(org-todo :wk "Org [T]odo")
      "m B" '(org-babel-tangle :wk "Org [B]abel tangle")
      "m T" '(org-todo-list :wk "Org [T]odo list"))

   (iron/leader-keys
      "m b" '(:ignore t :wk "Tables")
      "m b -" '(org-table-insert-hline :wk "Insert hline in table"))

   (iron/leader-keys
      "m d" '(:ignore t :wk "Date/deadline")
      "m d t" '(org-time-stamp :wk "Org time stamp"))

   (iron/leader-keys
      "o" '(:ignore t :wk "[O]pen")
      "o d" '(dashboard-open :wk "[D]ashboard")
      "o e" '(elfeed :wk "[E]lfeed RSS")
      "o f" '(make-frame :wk "Open buffer in new [F]rame")
      "o F" '(select-frame-by-name :wk "Select [F]rame by name"))

   (iron/leader-keys
      "p" '(projectile-command-map :wk "[P]rojectile"))

   (iron/leader-keys
      "s" '(:ignore t :wk "[S]earch")
      "s d" '(dictionary-search :wk "Search [D]ictionary")
      "s m" '(man :wk "[M]an pages")
      "s t" '(tldr :wk "Lookup [T]LDR docs for a command")
      "s w" '(woman :wk "[W]oman pages: similar to man but doesn't require man"))

   (iron/leader-keys
      "t" '(:ignore t :wk "[T]oggle")
      "t e" '(eshell-toggle :wk "Toggle [E]shell")
      "t f" '(flycheck-mode :wk "Toggle [F]lycheck")
      "t l" '(display-line-numbers-mode :wk "Toggle [L]ine numbers")
      "t n" '(neotree-toggle :wk "Toggle [N]eotree file viewer")
      "t o" '(org-mode :wk "Toggle [O]rg mode")
      "t r" '(rainbow-mode :wk "Toggle [R]ainbow mode")
      "t t" '(visual-line-mode :wk "Toggle [T]runcated lines")
      "t v" '(vterm-toggle :wk "Toggle [V]term"))

   (iron/leader-keys
      "w" '(:ignore t :wk "[W]indows")
      ;; Window splits
      "w c" '(evil-window-delete :wk "[C]lose window")
      "w n" '(evil-window-new :wk "[N]ew window")
      "w s" '(evil-window-split :wk "Horizontal [S]plit window")
      "w v" '(evil-window-vsplit :wk "[V]ertical split window")
      ;; Window motions
      "w h" '(evil-window-left :wk "Window left [H]")
      "w j" '(evil-window-down :wk "Window down [J]")
      "w k" '(evil-window-up :wk "Window up [K]")
      "w l" '(evil-window-right :wk "Window right [L]")
      "w w" '(evil-window-next :wk "Goto next [W]indow")
      ;; Move Windows
      "w H" '(buf-move-left :wk "Buffer move left [H]")
      "w J" '(buf-move-down :wk "Buffer move down [J]")
      "w K" '(buf-move-up :wk "Buffer move up [K]")
      "w L" '(buf-move-right :wk "Buffer move right [L]"))
  )
#+end_src

* GIT PROGRAMS
** Git Time Machine
[[https://github.com/emacsmirror/git-timemachine][git-timemachine]] is a program that allows you to move backwards and forwards through a file's commits.  'SPC g t' will open the time machine on a file if it is in a git repo.  Then, while in normal mode, you can use 'CTRL-j' and 'CTRL-k' to move backwards and forwards through the commits.

#+begin_src emacs-lisp
  (use-package git-timemachine
    :after git-timemachine
    :ensure t
    :hook (evil-normalize-keymaps . git-timemachine-hook)
    :config
      (evil-define-key 'normal git-timemachine-mode-map (kbd "C-j") 'git-timemachine-show-previous-revision)
      (evil-define-key 'normal git-timemachine-mode-map (kbd "C-k") 'git-timemachine-show-next-revision)
  )
#+end_src

** Magit
[[https://magit.vc/manual/][Magit]] is a full-featured git client for Emacs.

#+begin_src emacs-lisp
;; (use-package magit :ensure t)
#+end_src

* HIGHLIGHT TODO
Adding highlights to TODO and related words.

#+begin_src emacs-lisp
  (use-package hl-todo
    :ensure t
    :hook ((org-mode . hl-todo-mode)
           (prog-mode . hl-todo-mode))
    :config
    (setq hl-todo-highlight-punctuation ":"
          hl-todo-keyword-faces
          `(("TODO"       warning bold)
            ("FIXME"      error bold)
            ("HACK"       font-lock-constant-face bold)
            ("REVIEW"     font-lock-keyword-face bold)
            ("NOTE"       success bold)
            ("DEPRECATED" font-lock-doc-face bold))))
#+end_src

* IVY (COUNSEL)
+ Ivy, a generic completion mechanism for Emacs.
+ Counsel, a collection of Ivy-enhanced versions of common Emacs commands.
+ Ivy-rich allows us to add descriptions alongside the commands in M-x.

#+begin_src emacs-lisp
  (use-package counsel
    :after ivy
    :ensure t
    :diminish
    :config (counsel-mode))

  (use-package ivy
    :ensure t
    :bind
    ;; ivy-resume resumes the last Ivy-based completion.
    (("C-c C-r" . ivy-resume)
     ("C-x B" . ivy-switch-buffer-other-window))
    :diminish
    :custom
    (setq ivy-use-virtual-buffers t)
    (setq ivy-count-format "(%d/%d) ")
    (setq enable-recursive-minibuffers t)
    :config
    (ivy-mode))

  (use-package all-the-icons-ivy-rich
    :ensure t
    :init (all-the-icons-ivy-rich-mode 1))

  (use-package ivy-rich
    :after ivy
    :ensure t
    :demand t
    :init (ivy-rich-mode 1) ;; this gets us descriptions in M-x.
    :custom
    (ivy-virtual-abbreviate 'full
     ivy-rich-switch-buffer-align-virtual-buffer t
     ivy-rich-path-style 'abbrev)
    :config
    (ivy-set-display-transformer 'ivy-switch-buffer
                                 'ivy-rich-switch-buffer-transformer))
#+end_src

* LANGUAGE SUPPORT
Emacs has built-in programming language modes for Lisp, Scheme, DSSSL, Ada, ASM, AWK, C, C++, Fortran, Icon, IDL (CORBA), IDLWAVE, Java, Javascript, M4, Makefiles, Metafont, Modula2, Object Pascal, Objective-C, Octave, Pascal, Perl, Pike, PostScript, Prolog, Python, Ruby, Simula, SQL, Tcl, Verilog, and VHDL.  Other languages will require you to install additional modes.

#+begin_src emacs-lisp
(use-package haskell-mode :ensure t)
(use-package lua-mode :ensure t)

;; Configure lsp-mode
(use-package lsp-mode
  :ensure t
  :commands (lsp lsp-deferred)
  :config
  (setq lsp-prefer-flymake nil))

(use-package lsp-ui
  :ensure t
  :commands lsp-ui-mode)

(use-package company-lsp
  :ensure t
  :commands company-lsp)
#+end_src

** Golang Config

#+begin_src emacs-lisp
;; Install and configure go-mode
(use-package go-mode
  :ensure t
  :hook ((go-mode . lsp-deferred)
	 (before-save . gofmt-before-save))
  :config
  (setq tab-width 4)
  (setq indent-tabs-mode 1))

;; Function to run the current Go file
(defun my-go-run ()
  "Run the current Go file."
  (interactive)
  (let ((compile-command (concat "go run " buffer-file-name)))
    (compile compile-command)))

;; Function to build the current Go project
(defun my-go-build ()
  "Build the current Go project."
  (interactive)
  (compile "go build"))

;; Function to test the current Go project
(defun my-go-test ()
  "Test the current Go project."
  (interactive)
  (compile "go test ./..."))

;; Add key bindings for Go commands
(add-hook 'go-mode-hook
          (lambda ()
            (local-set-key (kbd "C-c C-r") 'my-go-run)
            (local-set-key (kbd "C-c C-b") 'my-go-build)
            (local-set-key (kbd "C-c C-t") 'my-go-test)))
#+end_src

* MINIBUFFER ESCAPE
By default, Emacs requires you to hit ESC three times to escape quit the minibuffer.  

#+begin_src emacs-lisp
  (global-set-key [escape] 'keyboard-escape-quit)
#+end_src

* MODELINE
The modeline is the bottom status bar that appears in Emacs windows.  While you can create your own custom modeline, why go to the trouble when Doom Emacs already has a nice modeline package available.  For more information on what is available to configure in the Doom modeline, check out: [[https://github.com/seagle0128/doom-modeline][Doom Modeline]]

#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1)
    :config
    (setq doom-modeline-height 35      ;; sets modeline height
          doom-modeline-bar-width 5    ;; sets right bar width
          doom-modeline-persp-name t   ;; adds perspective name to modeline
          doom-modeline-persp-icon t)) ;; adds folder icon next to persp name
#+end_src

* NEOTREE
Neotree is a file tree viewer.  When you open neotree, it jumps to the current file thanks to neo-smart-open.  The neo-window-fixed-size setting makes the neotree width be adjustable.  NeoTree provides following themes: classic, ascii, arrow, icons, and nerd.  Theme can be configed by setting "two" themes for neo-theme: one for the GUI and one for the terminal.  I like to use 'SPC t' for 'toggle' keybindings, so I have used 'SPC t n' for toggle-neotree.

| COMMAND        | DESCRIPTION               | KEYBINDING |
|----------------+---------------------------+------------|
| neotree-toggle | /Toggle neotree/            | SPC t n    |
| neotree- dir   | /Open directory in neotree/ | SPC d n    |

#+BEGIN_SRC emacs-lisp
  (use-package neotree
    :ensure t
    :config
    (setq neo-smart-open t
          neo-show-hidden-files t
          neo-window-width 55
          neo-window-fixed-size nil
          inhibit-compacting-font-caches t
          projectile-switch-project-action 'neotree-projectile-action) 
          ;; truncate long file names in neotree
          (add-hook 'neo-after-create-hook
             #'(lambda (_)
                 (with-current-buffer (get-buffer neo-buffer-name)
                   (setq truncate-lines t)
                   (setq word-wrap nil)
                   (make-local-variable 'auto-hscroll-mode)
                   (setq auto-hscroll-mode nil)))))

  ;; show hidden files
#+end_src

* ORG MODE
** Enabling Table of Contents
#+begin_src emacs-lisp
  (use-package toc-org
      :ensure t
      :demand t
      :commands toc-org-enable
      :init (add-hook 'org-mode-hook 'toc-org-enable))
#+end_src

** Enabling Org Bullets
Org-bullets gives us attractive bullets rather than asterisks.

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'org-indent-mode)
  (use-package org-bullets :ensure t)
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

** Diminish Org Indent Mode
Removes "Ind" from showing in the modeline.

#+begin_src emacs-lisp
  (eval-after-load 'org-indent '(diminish 'org-indent-mode))
#+end_src

** Org Level Headers
#+begin_src emacs-lisp
  (custom-set-faces
   '(org-level-1 ((t (:inherit outline-1 :height 1.7))))
   '(org-level-2 ((t (:inherit outline-2 :height 1.6))))
   '(org-level-3 ((t (:inherit outline-3 :height 1.5))))
   '(org-level-4 ((t (:inherit outline-4 :height 1.4))))
   '(org-level-5 ((t (:inherit outline-5 :height 1.3))))
   '(org-level-6 ((t (:inherit outline-5 :height 1.2))))
   '(org-level-7 ((t (:inherit outline-5 :height 1.1)))))
#+end_src

** Source Code Block Tag Expansion
Org-tempo is not a separate package but a module within org that can be enabled.  Org-tempo allows for '<s' followed by TAB to expand to a begin_src tag.  Other expansions available include:

| Typing the below + TAB | Expands to ...                          |
|------------------------+-----------------------------------------|
| <a                     | '#+BEGIN_EXPORT ascii' … '#+END_EXPORT  |
| <c                     | '#+BEGIN_CENTER' … '#+END_CENTER'       |
| <C                     | '#+BEGIN_COMMENT' … '#+END_COMMENT'     |
| <e                     | '#+BEGIN_EXAMPLE' … '#+END_EXAMPLE'     |
| <E                     | '#+BEGIN_EXPORT' … '#+END_EXPORT'       |
| <h                     | '#+BEGIN_EXPORT html' … '#+END_EXPORT'  |
| <l                     | '#+BEGIN_EXPORT latex' … '#+END_EXPORT' |
| <q                     | '#+BEGIN_QUOTE' … '#+END_QUOTE'         |
| <s                     | '#+BEGIN_SRC' … '#+END_SRC'             |
| <v                     | '#+BEGIN_VERSE' … '#+END_VERSE'         |

#+begin_src emacs-lisp 
  (require 'org-tempo)
#+end_src

* PERSPECTIVE
[[https://github.com/nex3/perspective-el][Perspective]] provides multiple named workspaces (or "perspectives") in Emacs, similar to multiple desktops in window managers.  Each perspective has its own buffer list and its own window layout, along with some other isolated niceties, like the [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Xref.html][xref]] ring.

#+begin_src emacs-lisp
  (use-package perspective
    :ensure t
    :demand t
    :custom
    ;; NOTE! I have also set 'SCP =' to open the perspective menu.
    ;; I'm only setting the additional binding because setting it
    ;; helps suppress an annoying warning message.
    (persp-mode-prefix-key (kbd "C-c M-p"))
    :init 
    (persp-mode)
    :config
    ;; Sets a file to write to when we save states
    (setq persp-state-default-file "~/.config/emacs/sessions"))

  ;; This will group buffers by persp-name in ibuffer.
  (add-hook 'ibuffer-hook
            (lambda ()
              (persp-ibuffer-set-filter-groups)
              (unless (eq ibuffer-sorting-mode 'alphabetic)
                (ibuffer-do-sort-by-alphabetic))))

  ;; Automatically save perspective states to file when Emacs exits.
  (add-hook 'kill-emacs-hook #'persp-state-save)
#+end_src

* PROJECTILE
[[https://github.com/bbatsov/projectile][Projectile]] is a project interaction library for Emacs.  It should be noted that many projectile commands do not work if you have set "fish" as the "shell-file-name" for Emacs.  I had initially set "fish" as the "shell-file-name" in the Vterm section of this config, but oddly enough I changed it to "bin/sh" and projectile now works as expected, and Vterm still uses "fish" because my default user "sh" on my Linux system is "fish".

#+begin_src emacs-lisp
  (use-package projectile
    :ensure t
    :config
    (projectile-mode 1))
#+end_src

* RAINBOW MODE
Display the actual color as a background for any hex color value (ex. #ffffff).  The code block below enables rainbow-mode in all programming modes (prog-mode) as well as org-mode, which is why rainbow works in this document.  

#+begin_src emacs-lisp
  (use-package rainbow-mode
    :ensure t
    :diminish
    :hook 
    ((org-mode prog-mode) . rainbow-mode))
#+end_src

* SANE DEFAULTS
The following settings are simple modes that are enabled (or disabled) so that Emacs functions more like you would expect a proper editor/IDE to function.

#+begin_src emacs-lisp
  (delete-selection-mode 1)    ;; You can select text and delete it by typing.
  (electric-indent-mode -1)    ;; Turn off the weird indenting that Emacs does by default.
  (electric-pair-mode 1)       ;; Turns on automatic parens pairing
  ;; The following prevents <> from auto-pairing when electric-pair-mode is on.
  ;; Otherwise, org-tempo is broken when you try to <s TAB...
  (add-hook 'org-mode-hook (lambda ()
             (setq-local electric-pair-inhibit-predicate
                     `(lambda (c)
                    (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c))))))
  (global-auto-revert-mode t)  ;; Automatically show changes if the file has changed
  (global-display-line-numbers-mode 1) ;; Display line numbers
  (global-visual-line-mode t)  ;; Enable truncated lines
  (menu-bar-mode -1)           ;; Disable the menu bar 
  (scroll-bar-mode -1)         ;; Disable the scroll bar
  (tool-bar-mode -1)           ;; Disable the tool bar
  (setq org-edit-src-content-indentation 0) ;; Set src block automatic indent to 0 instead of 2.
#+end_src

* SHELLS AND TERMINALS
In my configs, all of my shells (bash, fish, zsh and the ESHELL) require my shell-color-scripts-git package to be installed.  On Arch Linux, you can install it from the AUR.  Otherwise, go to my shell-color-scripts repository on GitLab to get it.

** Eshell
Eshell is an Emacs 'shell' that is written in Elisp.

#+begin_src emacs-lisp
  (use-package eshell-syntax-highlighting
    :after esh-mode
    :ensure t
    :config
    (eshell-syntax-highlighting-global-mode +1))

  ;; eshell-syntax-highlighting -- adds fish/zsh-like syntax highlighting.
  ;; eshell-rc-script -- your profile for eshell; like a bashrc for eshell.
  ;; eshell-aliases-file -- sets an aliases file for the eshell.
    
  (setq eshell-rc-script (concat user-emacs-directory "eshell/profile")
        eshell-aliases-file (concat user-emacs-directory "eshell/aliases")
        eshell-history-size 5000
        eshell-buffer-maximum-lines 5000
        eshell-hist-ignoredups t
        eshell-scroll-to-bottom-on-input t
        eshell-destroy-buffer-when-process-dies t
        eshell-visual-commands'("bash" "fish" "htop" "ssh" "top" "zsh"))
#+end_src

** Vterm
Vterm is a terminal emulator within Emacs.  The 'shell-file-name' setting sets the shell to be used in M-x shell, M-x term, M-x ansi-term and M-x vterm.  By default, the shell is set to 'fish' but could change it to 'bash' or 'zsh' if you prefer.

#+begin_src emacs-lisp
  (use-package vterm
    :ensure t
    :config
  (setq shell-file-name "/bin/zsh"
        vterm-max-scrollback 5000))
#+end_src

** Vterm-Toggle 
[[https://github.com/jixiuf/vterm-toggle][vterm-toggle]] toggles between the vterm buffer and whatever buffer you are editing.

#+begin_src emacs-lisp
  (use-package vterm-toggle
    :after vterm
    :ensure t
    :config
    (setq vterm-toggle-fullscreen-p nil)
    (setq vterm-toggle-scope 'project)
    (add-to-list 'display-buffer-alist
                 '((lambda (buffer-or-name _)
                       (let ((buffer (get-buffer buffer-or-name)))
                         (with-current-buffer buffer
                           (or (equal major-mode 'vterm-mode)
                               (string-prefix-p vterm-buffer-name (buffer-name buffer))))))
                    (display-buffer-reuse-window display-buffer-at-bottom)
                    ;;(display-buffer-reuse-window display-buffer-in-direction)
                    ;;display-buffer-in-direction/direction/dedicated is added in emacs27
                    ;;(direction . bottom)
                    ;;(dedicated . t) ;dedicated is supported in emacs27
                    (reusable-frames . visible)
                    (window-height . 0.3))))
#+end_src

* SUDO EDIT
[[https://github.com/nflath/sudo-edit][sudo-edit]] gives us the ability to open files with sudo privileges or switch over to editing with sudo privileges if we initially opened the file without such privileges.

#+begin_src emacs-lisp
  (use-package sudo-edit :ensure t)
#+end_src

* THEME
The first of the two lines below designates the directory where will place all of our themes.  The second line loads our chosen theme which is *dtmacs*, a theme that I created with the help of the [[https://emacsfodder.github.io/emacs-theme-editor/][Emacs Theme Editor]].

#+begin_src emacs-lisp
  (add-to-list 'custom-theme-load-path "~/.config/emacs/themes/")
  (use-package doom-themes
    :ensure t
    :config
    (setq doom-themes-enable-bold t
  	doom-themes-enable-italic t)
    (load-theme 'doom-zenburn t)
    (doom-themes-neotree-config)
    (doom-themes-org-config))

  ;; (load-theme 'kanagawa t)
#+end_src

* TLDR

#+begin_src emacs-lisp
  (use-package tldr :ensure t)
#+end_src

* TRANSPARENCY

#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(alpha-background . 100))
#+end_src

* WHICH-KEY

#+begin_src emacs-lisp
  (use-package which-key
    :ensure t
    :demand t
    :init
      (which-key-mode 1)
    :diminish
    :config
    (setq which-key-side-window-location 'bottom
  	  which-key-sort-order #'which-key-key-order-alpha
  	  which-key-sort-uppercase-first nil
  	  which-key-add-column-padding 1
  	  which-key-max-display-columns nil
  	  which-key-min-display-lines 6
  	  which-key-side-window-slot -10
  	  which-key-side-window-max-height 0.25
  	  which-key-idle-delay 0.8
  	  which-key-max-description-length 25
  	  which-key-allow-imprecise-window-fit nil
  	  which-key-separator " → " ))
#+end_src
