# Laptop Host Configuration
{ config, lib, pkgs, inputs, ... }:

{
  imports = [
    # Hardware configuration will be generated by nixos-generate-config
    # ./hardware-configuration.nix
    
    # Import desktop configuration as base
    ../desktop
  ];

  # Override desktop hostname
  networking.hostName = lib.mkForce "nixos-laptop";

  # Laptop-specific configurations
  
  # Power management
  services.tlp = {
    enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
      
      START_CHARGE_THRESH_BAT0 = 20;
      STOP_CHARGE_THRESH_BAT0 = 80;
      
      WIFI_PWR_ON_AC = "off";
      WIFI_PWR_ON_BAT = "on";
    };
  };

  # Battery and power management
  services.upower.enable = true;
  powerManagement.enable = true;

  # Laptop display management
  services.autorandr.enable = true;

  # Trackpad support
  services.libinput = {
    enable = true;
    touchpad = {
      naturalScrolling = true;
      tapping = true;
      clickMethod = "buttonareas";
    };
  };

  # Laptop-specific packages
  environment.systemPackages = with pkgs; [
    # Battery monitoring
    acpi
    powertop
    
    # Display management
    autorandr
    
    # Laptop utilities
    brightnessctl
  ];

  # Enable laptop-specific services
  services.thermald.enable = true; # Intel thermal management
  
  # Bluetooth for laptop
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
}
